version: '1'
services:
  redis:
    image: redis/redis-stack-server:latest
    hostname: redis-stack-server
    restart: always
    ports:
      - 8010:6379

  web:
    build:
      dockerfile: Dockerfile

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
